#!/usr/bin/env bash

save_profile() {
  local -n _selected=$1
  local os_name
  os_name=$(detect_os)

  declare -A all_scripts=()
  if [ -f "$ACTIVE_FILE" ]; then
    local in_scripts=false
    while IFS= read -r line; do
      [[ "$line" == "[scripts]" ]] && in_scripts=true && continue
      if $in_scripts && [[ "$line" =~ ^([a-zA-Z0-9_-]+)[[:space:]]*=[[:space:]]*(true|false)$ ]]; then
        all_scripts["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
      fi
    done < "$ACTIVE_FILE"
  fi

  for s in "${_selected[@]}"; do
    all_scripts["${s%.sh}"]="true"
  done

  {
    echo "# Generated by setup.sh"
    echo "os = \"$os_name\""
    echo ""
    echo "[scripts]"
    for name in "${!all_scripts[@]}"; do
      echo "$name = ${all_scripts[$name]}"
    done
  } > "$ACTIVE_FILE"

  clear
  echo
  echo "# ======================================"
  echo "Setup complete!"
  echo " > Active profile saved to: $ACTIVE_FILE"
}
